"""empty message

Revision ID: 3acaee69c943
Revises: 
Create Date: 2025-03-15 21:28:50.996539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3acaee69c943'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abonents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abon_name', sa.String(length=128), nullable=False),
    sa.Column('phone_number', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('Connection', 'Active', 'Blocking', 'Debtor', 'On_termination', 'Terminated', name='abonstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_service', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('switches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_com', sa.String(length=256), nullable=False),
    sa.Column('IP', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('login', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('admin', 'appruved_user', 'unknown_user', name='role'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('login')
    )
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=256), nullable=False),
    sa.Column('com_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['com_id'], ['switches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name_port', sa.String(length=256), nullable=False),
    sa.Column('status_link', sa.Enum('Connected', 'Disconnected', name='linkstatus'), nullable=False),
    sa.Column('switch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['switch_id'], ['switches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=False),
    sa.Column('osmp', sa.Integer(), nullable=False),
    sa.Column('abon_name', sa.String(length=128), nullable=False),
    sa.Column('date_d', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('abon_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['abon_id'], ['abonents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('osmp'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('offer_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('topic', sa.String(length=128), nullable=False),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=True),
    sa.Column('date_from', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=True),
    sa.Column('date_to', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=True),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('assign_to', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assign_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('offer_services')
    op.drop_table('offers')
    op.drop_table('ports')
    op.drop_table('addresses')
    op.drop_table('users')
    op.drop_table('switches')
    op.drop_table('services')
    op.drop_table('abonents')
    # ### end Alembic commands ###
